server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      - id: microservice_back
        uri: http://localhost:9001
        predicates: Path=/patient/**
        filters:
          - PrefixPath=/microservice_back/v1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Medilabo-Solutions-realm
