server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-Origins: "https:localhost:4200", "https:microservice-front:4200"
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            
      routes:
      - id: microservice_back
        uri: http://localhost:9001
        predicates: Path=/patient/**
        filters:
          - PrefixPath=/microservice_back/v1

