server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      - id: microservice_backend_patient
        uri: lb://microservice-backend-patient
        predicates: Path=/patient/**
        filters:
          - PrefixPath=/microservice_backend_patient/v1
      - id: microservice_backend_note
        uri: lb://microservice-backend-note
        predicates: Path=/note/**
        filters:
          - PrefixPath=/microservice_backend_note/v1
      - id: microservice_backend_assessor_assessor
        uri: lb://microservice-backend-assessor
        predicates:  Path=/assessor/**
        filters:
          - PrefixPath=/microservice_backend_assessor/v1
      - id: microservice_backend_assessor_trigger
        uri: lb://microservice-backend-assessor
        predicates: Path=/trigger/**
        filters:
          - PrefixPath=/microservice_backend_assessor/v1
