server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Controle-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https:localhost:4200"
            allowedMethods: "*"
            
      routes:
      - id: microservice_back
        uri: http://localhost:9001
        predicates: Path=/patient/**
        filters:
          - PrefixPath=/microservice_back/v1

