server:
  port: 9000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https:localhost:4200"
            allowedMethods:
            - GET
            - POST
            - PATCH
            - DELETE
      routes:
      - id: microservice_back
        uri: http://localhost:9001
        predicates: Path=/patient/**
        filters:
          - PrefixPath=/microservice_back/v1
# security:
#   oauth2:
#     client:
#       registration:
#         gateway:
#           client-id: gateway
#           client-secret: VSoxAhJrROMvJK54NmxQt5VHwJYlzTkY
#           authorization-grant-type: authorization_code
#           redirect-uri: http://localhost:4200/
