server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      routes:
      - id: microservice_back
        uri: http://localhost:9001
        predicates: Path=/patient/**
        filters:
          - PrefixPath=/microservice_back/v1
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/Medilabo-Solutions-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gateway
            client-secret: VSoxAhJrROMvJK54NmxQt5VHwJYlzTkY
